In [2]:
import xml.etree.cElementTree as et
import pandas as pd
 
def getnodevalue(node):
    """ return node  or None """
    return node if node is not None else None

def main():
    """ main """
    parsed_xml = et.parse("activationData.xml")
    dfxmlcols = ['EventId', 'InvestigationType', 'AccidentNumber', 'EventDate', 'Location', 
    'Country', 'Latitude', 'Longitude'
]
    dffromxml = pd.DataFrame(columns=dfxmlcols)
 
    for a in parsed_xml.getroot():
        for node in a:
            ID = node.attrib.get('EventId')
            type = node.attrib.get('InvestigationType')
            Anumber = node.attrib.get('AccidentNumber')
            Edate = node.attrib.get('EventDate')
            Location = node.attrib.get('Location')
            type = node.attrib.get('InvestigationType')
            Country = node.attrib.get('Country')
            Latitude = node.attrib.get('Latitude')
            dffromxml = dffromxml.append(
                pd.Series([ID, getnodevalue(type), getnodevalue(Anumber),
                       getnodevalue(Edate), getnodevalue(Location),getnodevalue(type),getnodevalue(Country),
                       getnodevalue(Latitude) ], index=dfxmlcols),
            ignore_index=True)
    print (dffromxml.head())
main()

          EventId InvestigationType AccidentNumber   EventDate  \
0  20200603X63830          Accident     ANC20CA056  06/01/2020
1  20200601X45921          Accident     CEN20CA204  06/01/2020
2  20200601X20239          Accident     ERA20CA201  06/01/2020
3  20200601X50402          Accident     ERA20CA203  06/01/2020
4  20200601X90852          Accident     CEN20CA206  05/31/2020

             Location   Country       Latitude  Longitude
0         Nikiski, AK  Accident  United States  60.935277
1          Denver, CO  Accident  United States  39.794166
2  GULF OF MEXICO, GM  Accident  United States  24.916667
3         Batavia, NY  Accident  United States  43.031667
4     Worthington, MN  Accident  United States  43.655556

In [3]:
#xml has different structure
import pandas as pd 
import xml.etree.ElementTree as et 

dftree = et.parse("activation.xml")
dfroot = dftree.getroot() 

dfxmlCols = ['EventId', 'InvestigationType', 'AccidentNumber', 'EventDate']
rows = []

for node in dfroot: 
    EventId = node.attrib.get("EventId") if node is not None else None
    InvestigationType = node.get("InvestigationType") if node is not None else None
    AccidentNumber = node.get("AccidentNumber") if node is not None else None
    EventDate = node.get("EventDate") if node is not None else None
    
    rows.append({"EventId": EventId, "InvestigationType": InvestigationType, 
                 "AccidentNumber":AccidentNumber, "EventDate": EventDate})

out_df = pd.DataFrame(rows, columns = dfxmlCols)
out_df.head()

          EventId InvestigationType AccidentNumber   EventDate
0  20200603X63830          Accident     ANC20CA056  06/01/2020
1  20200601X45921          Accident     CEN20CA204  06/01/2020
2  20200601X20239          Accident     ERA20CA201  06/01/2020
3  20200601X50402          Accident     ERA20CA203  06/01/2020
4  20200601X90852          Accident     CEN20CA206  05/31/2020

In [4]:
import pandas as pd 
import xml.etree.ElementTree as et 

dftree = et.parse("activationData.xml")
dfroot = dftree.getroot() 

dfxmlCols = ['EventId', 'InvestigationType', 'AccidentNumber', 'EventDate']
rows = []

for a in dfroot: 
    for node in a:
        EventId = node.attrib.get("EventId") if node is not None else None
        InvestigationType = node.get("InvestigationType") if node is not None else None
        AccidentNumber = node.get("AccidentNumber") if node is not None else None
        EventDate = node.get("EventDate") if node is not None else None
        rows.append({"EventId": EventId, "InvestigationType": InvestigationType, 
                 "AccidentNumber":AccidentNumber, "EventDate": EventDate})

out_df0 = pd.DataFrame(rows, columns = dfxmlCols)
out_df0.head()

          EventId InvestigationType AccidentNumber   EventDate
0  20200603X63830          Accident     ANC20CA056  06/01/2020
1  20200601X45921          Accident     CEN20CA204  06/01/2020
2  20200601X20239          Accident     ERA20CA201  06/01/2020
3  20200601X50402          Accident     ERA20CA203  06/01/2020
4  20200601X90852          Accident     CEN20CA206  05/31/2020

In [5]:
#xml has different structure
import pandas as pd 
import xml.etree.ElementTree as et 

dftree = et.parse("activationData.xml")
dfroot = dftree.getroot() 
dfroot=dfroot[0]
dfxmlCols = ['EventId', 'InvestigationType', 'AccidentNumber', 'EventDate']
rows = []

for node in dfroot: 
    EventId = node.attrib.get("EventId") if node is not None else None
    InvestigationType = node.get("InvestigationType") if node is not None else None
    AccidentNumber = node.get("AccidentNumber") if node is not None else None
    EventDate = node.get("EventDate") if node is not None else None
    
    rows.append({"EventId": EventId, "InvestigationType": InvestigationType, 
                 "AccidentNumber":AccidentNumber, "EventDate": EventDate})

out_df = pd.DataFrame(rows, columns = dfxmlCols)
out_df.head()

          EventId InvestigationType AccidentNumber   EventDate
0  20200603X63830          Accident     ANC20CA056  06/01/2020
1  20200601X45921          Accident     CEN20CA204  06/01/2020
2  20200601X20239          Accident     ERA20CA201  06/01/2020
3  20200601X50402          Accident     ERA20CA203  06/01/2020
4  20200601X90852          Accident     CEN20CA206  05/31/2020